sudo: required
services:
    - docker

before_install:
    - docker build -t bordwalk2000/docker-react -f dockerfile.dev .

script: 
    - docker run -e CI=true bordwalk2000/docker-react npm run test

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "arn:aws:s3:::elasticbeanstalk-us-east-2-077209259484"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY2
    secret_access_key: $AWS_SECRET_KEY2
